"""This module is responsible for parsing the list of tokens generated by the lexer into an AST."""


from dataclasses import dataclass
from typing import List, cast
from lexing import Token, Plus, Star, Number


@dataclass
class Expression:
    """Base class for all expressions contained in the AST."""


# Add Expression as base class to Number after initialization to avoid circular import
Number.__bases__ = (Expression,)


@dataclass
class Add(Expression):
    """Expression of the form: expr_left + expr_right"""
    left: Expression
    right: Expression


@dataclass
class Multiply(Expression):
    """Expression of the form: expr_left * expr_right"""
    left: Expression
    right: Expression


def parse(tokens: List[Token]) -> Expression:
    """Parses a list of tokens into an AST."""
    lookahead = 0
    terms: List[Token|Expression] = []
    expr: Token|Expression

    for i, expr in enumerate(tokens):
        if lookahead > 0:
            lookahead -= 1
            continue
        if isinstance(expr, Star):
            arg1: Token | Expression = terms.pop() # remove arg1 from ast
            arg2: Token | Expression = tokens[i + 1]
            assert isinstance(arg1, Expression)
            assert isinstance(arg2, Expression)
            terms.append(Multiply(arg1, arg2))
            lookahead = 1 # remove arg2 from ast
        else:
            terms.append(expr)

    ast: List[Token|Expression] = []

    for i, expr in enumerate(terms):
        if lookahead > 0:
            lookahead -= 1
            continue
        if isinstance(expr, Plus):
            arg1 = ast.pop() # remove arg1 from ast
            arg2 = terms[i + 1]
            assert isinstance(arg1, Expression)
            assert isinstance(arg2, Expression)
            ast.append(Add(arg1, arg2))
            lookahead = 1 # remove arg2 from ast
        else:
            ast.append(expr)

    assert len(ast) == 1
    return cast(Expression, ast[0])
